name: Build and Deploy to EC2

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PROJECT_NAME: facebookPHP_project
  BUCKET_NAME: facebookphp-cicd-bucket
  CODE_DEPLOY_APP_NAME: facebookphp_cicd
  DEPLOYMENT_GROUP_NAME: facebookphp_instance
  ROOT_DB_HOST: ${{secrets.ROOT_DB_HOST}}
  ROOT_DB_NAME: ${{secrets.ROOT_DB_NAME}}
  ROOT_DB_PASSWORD: ${{secrets.ROOT_DB_PASSWORD}}
  ROOT_DB_USER: ${{secrets.ROOT_DB_USER}}
  ROOT_IP: ${{secrets.ROOT_IP}}
  MY_DB_HOST: ${{secrets.MY_DB_HOST}}
  MY_DB_NAME: ${{secrets.MY_DB_NAME}}
  MY_DB_PASSWORD: ${{secrets.MY_DB_PASSWORD}}
  MY_DB_USER: ${{secrets.MY_DB_USER}}
  MY_IP: ${{secrets.MY_IP}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make .env File
        run: |
          touch .env
          echo "IP=$ROOT_IP" >> .env
          echo "DB_HOST=$ROOT_DB_HOST" >> .env
          echo "DB_USER=$ROOT_DB_USER" >> .env
          echo "DB_PASSWORD=$ROOT_DB_PASSWORD" >> .env
          echo "DB_NAME=$ROOT_DB_NAME" >> .env
          cat .env

          touch ./web/.env
          echo "IP=$MY_IP" >> ./web/.env
          echo "DB_HOST=$MY_DB_HOST" >> ./web/.env
          echo "DB_USER=$MY_DB_USER" >> ./web/.env
          echo "DB_PASSWORD=$MY_DB_PASSWORD" >> ./web/.env
          echo "DB_NAME=$MY_DB_NAME" >> ./web/.env
          cat ./web/.env

      - name: Make Zip File
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PRIVATE_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy To EC2 instance
        run: aws deploy create-deployment 
                --application-name $CODE_DEPLOY_APP_NAME 
                --deployment-config-name CodeDeployDefault.AllAtOnce
                --deployment-group-name $DEPLOYMENT_GROUP_NAME 
                --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
                --region ap-southeast-2
